### ISSUE TITLE
Install link fails

### ISSUE THREAD

**Issue by henkin** [ToxyFlog1627/ProjectTaskConverterTodoistApp#1]
Clicking the install 'link' on the github page times out.

<img width="388" alt="image" src="https://github.com/ToxyFlog1627/ProjectTaskConverterTodoistApp/assets/5246441/0d1fc5e6-0cf8-4428-90d7-0e8bcd98c0a6">

I'm excited for this plugin! thanks for making it.

**Comment by ToxyFlog1627** [comment]
Hi,
It's very strange, I have just checked and it works for me. Does the whole page time out or the integrations window?
Luckily, I have recently been able to publish it and now you can find it in the list of all integrations. So you should try installing it from there.

**Comment by henkin** [comment]
Bizarre - this morning it opened right up for me. 🤷 
Cheers:
<img width="1076" alt="image" src="https://github.com/ToxyFlog1627/ProjectTaskConverterTodoistApp/assets/5246441/52984cd9-ff0e-4280-a990-330a66824eac">
Thanks!
