### ISSUE TITLE
Feature request - leave behind a link to created project

### ISSUE THREAD

**Issue by msucorey** [ToxyFlog1627/ProjectTaskConverterTodoistApp#2]
As a user who converts a task to a project, I want to see, in the place of the converted task, an uncompleteable task whose title is a markdown link to the new project I just created so that I can have a breadcrumb and be visually reminded where this work went.

**Comment by ToxyFlog1627** [comment]
It seems like a great idea!
What do you mean by uncompletable? AFAIK there is no such thing. I guess the closest alternative I can think of would be to make task repeatable.

**Comment by msucorey** [comment]
Just mean prefixing the task title with an asterisk, standard way of making a task uncompleteable.

**Comment by ToxyFlog1627** [comment]
OK, didn't know it is a thing.
Maybe instead prefix it with [Converted to task]?

**Comment by msucorey** [comment]
Yeah that would work too.  The real magic would be the link, essentially keeping the 'wiki' structure of your original setup.

**Comment by ToxyFlog1627** [comment]
I've added it.
Could you test it, and if everything works close the issue.

**Comment by msucorey** [comment]
Looks good!  Thank you for this - think it makes this feature even more awesome.
