### ISSUE TITLE
Converting task to project doesn't convert sub tasks

### ISSUE THREAD

**Issue by emsqrd** [ToxyFlog1627/ProjectTaskConverterTodoistApp#3]
I have a task with sub tasks. When I convert the task to a new project, the new project is created, but none of the subtasks are added to that new project. The new project is created and empty.

I've waited a few minutes, but still nothing. The screenshots are from latest version of Todoist on Windows 10 machine, but this also happens on web in Google Chrome.

![image](https://github.com/user-attachments/assets/a2d9f9c2-acee-4edd-83f8-5fbc97f46252)
![image](https://github.com/user-attachments/assets/9d1b7f74-d6ee-434a-8f2c-94cc8eb95596)

**Comment by ToxyFlog1627** [comment]
Hi,
Thanks for reaching out, it seems that Todoist made some small API changes.
I fixed it, could you check it?

**Comment by emsqrd** [comment]
Works like a champ. Thanks for the quick response!
